spring:
  application:
    name: ProvideMovie
server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true #注册服务使用的ip方式